# Generated by Django 4.2.4 on 2023-09-07 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bravoapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='air_date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='franchise',
            name='series_premier',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='season',
            name='premier_date',
            field=models.CharField(max_length=10),
        ),
    ]
